version: "3.9"
services:
    database:
        image: postgres:latest
        environment:
            POSTGRES_USER: medusa
            POSTGRES_PASSWORD: medusa
            POSTGRES_DB: medusa
        ports:
            - "5432:5432"
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
